//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventsID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public int SiteID { get; set; }
    
        public virtual TouristSite TouristSite { get; set; }
    }
}
