
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SitesDB
{

using System;
    using System.Collections.Generic;
    
public partial class SiteEvent
{

    public int ID { get; set; }

    public string EventDescription { get; set; }

    public Nullable<System.DateTime> DateOfEvent { get; set; }

    public int SiteID { get; set; }



    public virtual NationalSite NationalSite { get; set; }

}

}
